version: "2"

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=wordpress
    ports:
     - "3306:3306"

  wordpress:
    image: wordpress:4.4.2-apache
    links:
      - db
    ports:
      - "8000:80"
    volumes:
     - wordpress-data:/var/www/html
    environment:
     - WORDPRESS_DB_HOST=db:3306
     - WORDPRESS_DB_PASSWORD=test

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - db
      ports:
        - "8888:80"

volumes:
  wordpress-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/wordpress