- name: 'Installing dependencies'
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: 'Adding APT key'
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"

- name: 'Adding APT repository'
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release }} main"
    update_cache: yes

- name: 'Installing APT packages'
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-setuptools
    - docker-engine

- name: 'Installing Ansible dependencies'
  easy_install:
    name: pip

- name: 'Installing Ansible PIP dependencies'
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-py
    - docker-compose

- name: 'Downloading bash script to install local-persist driver for Docker'
  get_url:
    url: "https://raw.githubusercontent.com/CWSpear/local-persist/master/scripts/install.sh"
    dest: "/usr/local-persist-install.sh"

- name: "Execute above bash script"
  command: "bash /usr/local-persist-install.sh --upstart"